name: Build, push and deploy Image

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  id-token: write 
  contents: read 

env:
  AWS_REGION: us-east-1

jobs: 
  build:
    runs-on: ubuntu-latest # github runner
    steps:
      - name: clone repository
        uses: actions/checkout@v3
      - name: AWS credentials configuration
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.AWS_ROLE}} # OIDC
          aws-region: ${{ env.AWS_REGION }}
      - name: login to ECR
        uses: aws-actions/amazon-ecr-login@v1


